linters:
  enable:
    - bidichk
    - exportloopref
    - asciicheck
    - durationcheck
    - errchkjson
    - grouper
    - nilerr
    - predeclared
    - unconvert
    - wastedassign
    - misspell
    - errcheck
    - errorlint

linters-settings:
  misspell:
    locale: US
